<?php

/**
 * Custom Webform Validation to check for Emoji characters
 * https://www.drupal.org/node/908600
 */
function webform_emoji_webform_validation_validators() {
  return array(
    'emoji' => array(
      'name' => t('Emoji Characters'),
      'component_types' => array(
        'textarea',
        'textfield',
      ),
      'custom_error' => TRUE,
      'description' => t('Check for Emoji characters in user input.'),
    )
  );
}

function webform_emoji_webform_validation_validate($validator_name, $items, $components, $rule) {
  if ($items) {
    switch ($validator_name) {
      case 'emoji':
        // Search string: https://www.drupal.org/node/2043439#comment-8213973
        $emoticons = '/([0-9|#][\x{20E3}])|[\x{00ae}|\x{00a9}|\x{203C}|\x{2047}|\x{2048}|\x{2049}|\x{3030}|\x{303D}|\x{2139}|\x{2122}|\x{3297}|\x{3299}][\x{FE00}-\x{FEFF}]?|[\x{2190}-\x{21FF}][\x{FE00}-\x{FEFF}]?|[\x{2300}-\x{23FF}][\x{FE00}-\x{FEFF}]?|[\x{2460}-\x{24FF}][\x{FE00}-\x{FEFF}]?|[\x{25A0}-\x{25FF}][\x{FE00}-\x{FEFF}]?|[\x{2600}-\x{27BF}][\x{FE00}-\x{FEFF}]?|[\x{2900}-\x{297F}][\x{FE00}-\x{FEFF}]?|[\x{2B00}-\x{2BF0}][\x{FE00}-\x{FEFF}]?|[\x{1F000}-\x{1F6FF}][\x{FE00}-\x{FEFF}]?/u';
        
        foreach ($items as $key => $val) {
            $test = preg_match($emoticons, $val);
            _webform_validation_test($errors, $key, $rule, $test);
        }
        return $errors;
        break;
    }
  }
}